schemaVersion: 2.2.0
metadata:
  name: vscode-test-extension
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 1G
      memoryLimit: 4G
      cpuRequest: '1'
      cpuLimit: '2'

commands:
  - id: run-script
    exec:
      label: Run test script
      component: tools
      commandLine: /projects/vscode-test-extension/test.sh
