schemaVersion: 2.2.0
metadata:
  name: long-workspace-name-to-test-desktop-visual-studio-code
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 1G
      memoryLimit: 4G
      cpuRequest: '1'
      cpuLimit: '2'

commands:
  - id: install-dependencies
    exec:
      label: 1. Install dependencies
      component: tools
      commandLine: npm install
  - id: compile
    exec:
      label: 2. Compile
      component: tools
      commandLine: npm run compile
      group:
        kind: build
        isDefault: true
  - id: build-vsix
    exec:
      label: 3. Build vsix binary
      component: tools
      commandLine: npm run build-vsix
      group:
        kind: build
        isDefault: false
  - id: patch-che-code-server
    exec:
      # put your tooling container name here
      component: tools
      commandLine: |
        sed -i 's/process\.env\.DEVWORKSPACE_NAME\.length > 20/process\.env\.DEVWORKSPACE_NAME\.length > 100/g' /che-code-server/server/out/che-code-server.js
events:
  postStart:
    - patch-che-code-server
